### ISSUE TITLE
Feature Request: Ability to sort or organize apps and folders.

### ISSUE THREAD

**Issue by Miatadude** [nick-friedrich/launchie-launchpad-replacement-mac-os#10]
Need the ability to reorganize the apps and folders based on user preference.

**Comment by ssstraub** [comment]
I also would like this. Launchpad allowed the user to place icons anywhere in any order, not just alphabetically. It had drag and top icon arrangement, exactly the same as the iOS home screen. 

Launchie currently enforces a rigid alphabetical sort, which makes it a non-starter, for me, for replacing Launchpad. I will be tracking this project to see if it gets added over time though. Thanks!

**Comment by nick-friedrich** [comment]
Drag and drop works a little bit different, yes. Getting the preview animations correctly without glitches is a lot harder than i thought. That's why i decided to just highlight the position the app will be dragged to instead of animating everything like in the OG launchpad. 

When there is time, I will surely come back to the animation part, but for now i focus a lot on functionality

**Comment by Rubaka** [comment]
@nick-friedrich 
It would be good to have ability to drag and drop folders to a specific place or add them by default to the top before programs.

I've added folders recently, and they are randomly displayed (see the screenshot), I can't move them one after each other.

![Image](https://github.com/user-attachments/assets/70332865-b9f4-4cb3-873b-bb125086432d)

**Comment by Miatadude** [comment]
Hi Nick! Sorry for the brevity… I was rushed. I would like similar functionality that was lost with the update to v26. I like to put my various apps into folders that make sense for me, i.e. the folder “Connect” contains apps that connect to other devices like a VNC server or a printer. Other folders as example would be “Networking” for various network tools, “Photography”, “Audio-Video”, “System Utilities” etc. within the folders I would have the apps sorted alphabetically, or in order of preference (most used) etc. Outside the folders I keep a few apps by themselves that I use frequently, but do not want on the dock as there would be too many. These would be apps like Capture for my scanner, qBittorrent etc. What I would like is the flexibility to organize apps within or outside folders in Launchie however I need them, alphabetically or my own order.

Hope this clarifies.

Best regards.

PS Love your app BTW!

Ken

......sent from someplace else!

**Comment by nick-friedrich** [comment]
The bugs with the random order are fixed in the latest version. Default order (first start): alphabetical, after that you can customize the order as you like

**Comment by Rubaka** [comment]
@nick-friedrich It’s not fully fixed. Currently, the apps you add to folders are ordered based on the sequence they were moved into the folder. By default, apps inside folders should instead be sorted alphabetically by name. If a user wants a different arrangement, there should be an option to manually reorder them and save that order.

Also, while drag-and-drop for folders and apps is working, the behavior is confusing. To change positions, you need to drop a folder or app icon on top of another icon. In macOS, this same action creates a new folder with the two apps, which caused confusion. For example, when I tried to move a folder/app icon and drop it between two apps, it didn’t work as expected.
