### ISSUE TITLE
Launchi checks at start updates and ask for apple account

### ISSUE THREAD

**Issue by relama** [nick-friedrich/launchie-launchpad-replacement-mac-os#51]
One good thing with macbook is, that you are not forced to apply for apple account and use app store.
Unfortunately, launchie is checking updates at start and if you dont use an apple account a login window appears - that is a little bit annoying.

-> I would propose to have an option to switch off automatic update checks.
-> and add an oprtion to check updates manually

PS: I like launchie very much

**Comment by nick-friedrich** [comment]
Hello,

are you signed in to the Apple Account in the AppStore? Which version are you using? Homebrew or AppStore? Launchie checks for entitlements (if you are a pro version user). Maybe that's why Launchie is asking you to sign in? 

I never experienced the issue once, so it is hard to guess why this is happening

**Comment by relama** [comment]
I don use any apple account and therfore Im not signed in.

**Comment by relama** [comment]
After 1st start of launchie and also if I open "Updates & Info" menu a window with "Bei Apple Account anmelden" pops up.

**Comment by nick-friedrich** [comment]
Thank you for clarifying. I will fix this in upcoming versions.

**Comment by nick-friedrich** [comment]
Can you try this version? 

I am signed in on every device so I cannot test if this fixes this issue.

https://github.com/nick-friedrich/launchie-launchpad-replacement-mac-os/blob/test-version-non-apple-account/Launchie_1.2.12.dmg

**Comment by relama** [comment]
I have installed v1.2.12, but there is same issue with Apple account signing window. I think a potential solution could be to add in update menue an option to switch on/off the check vor newer versions.

BR+merry xmas

**Comment by nick-friedrich** [comment]
Should be resolved with the latest version

**Comment by relama** [comment]
I have tested the version 1.3. Unfortunately, this issue is not resolved. Apple account window appears again when Launchie AutoStart or 1st manual start or opening update/info menue (which is not a problem).

**Comment by relama** [comment]
I think this is related to a kind of used framework(s) (e.g. sparkle/swift) which by standard automatically checks for updates. This must be “active” deactivated – I guess AI will help you for code proposal….

**Comment by nick-friedrich** [comment]
Thanks for the additional feedback. Currently I have one codebase for the non-apple and apple version and at runtime the app checks if it's a appstore version or not. To truly get rid of this I would have to separate the code base's or heavily rely on Build flags. Would be hard to maintain, and the number of users who have the direct downloaded version + don't use an apple account is probably very low. 

I will still try to figure out a way to get around this.

**Comment by relama** [comment]
I understand that using build flags will lead to different codebases and binaries: One version for apple app store and one for direct download. And I agree that this should be prevented because of maintenance. Additionally there is a need for both apps to be signed/notarized with Apple (I would not recommend deploying such kind of app without an valid Apple sign). 

Maybe an solution could be to use runtime flags to switch on/off the apple services? ...but I'm almost lightyears away from being a developer ;-).

**Comment by Calab** [comment]
Just a note letting you know that I am also affected by this.

**Comment by relama** [comment]
After update to 26.4.1  (Launchi v1.3.5) no Apple account window appears - can sombody confirm?
